### ISSUE TITLE
error on deploying the app - please help.

### ISSUE THREAD

**Issue by harrywang** [kronosapiens/chef-repo#1]
@kronosapiens thanks a lot for the great tutorial. I am trying to learn OpsWorks by deploying Thena but running into an error: https://gist.github.com/harrywang/0fca5a14e728089da097

my stack setting:
<img width="977" alt="screenshot 2016-01-18 23 03 28" src="https://cloud.githubusercontent.com/assets/595772/12409419/ccfa34ea-be37-11e5-9a40-4d04ec6ff745.png">

layer (the deploy recipe created the error after starting the instance without it):
<img width="733" alt="screenshot 2016-01-18 23 04 53" src="https://cloud.githubusercontent.com/assets/595772/12409434/eaccce2e-be37-11e5-82de-0a4ab9426d5c.png">

Instance:
<img width="579" alt="screenshot 2016-01-18 23 07 23" src="https://cloud.githubusercontent.com/assets/595772/12409460/439ea040-be38-11e5-980e-f12a752ec52b.png">

App:
<img width="831" alt="screenshot 2016-01-18 23 05 57" src="https://cloud.githubusercontent.com/assets/595772/12409450/18226064-be38-11e5-843f-3e970018a1da.png">

Any idea? Thanks a lot!

**Comment by harrywang** [comment]
problem solved - your example is for Chef 11 on OpsWorks - I was using Chef 12 stack. Thanks anyway.

**Comment by kronosapiens** [comment]
Thanks for following through on this @harrywang !
